import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import useSWR from "swr";
import { useRef, useState } from "react";
import useSound from 'use-sound';

export default function Home() {

  const [play, setPlay] = useState<boolean>(false)
  const [playBase, playbaseData] = useSound('/let-the-mystery-unfold.mp3');
  const [playTrigger] = useSound('/bigbang.wav');

  const fetcher = (url: string) => fetch(url).then((res) => res.json());

  const { data, error } = useSWR("/api/trigger", fetcher, {
    refreshInterval: 100,
  });
 

  if (error) return "An error has occurred.";
  if (!data) return "Loading...";
  if (data) console.log("Data", data);
  if (data) console.log("Data Trigger", data.trigger);

  async function handleClick() {

   setPlay(true);
  };
  if( !play ){
    return <button onClick={handleClick}> Play</button>
  }
  if (!data.trigger) {
    // Base Line
    playBase();
    return (
      <div className={styles.container}>
        <Head>
          <title>Halloween 2022</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main >
        <div style={{ position: 'relative', width: "100vw", height: '100vh' }}>
      <Image
        alt="Mountains"
        src="/pumpkin.gif"
        fill
        sizes="100vw"
        style={{
          objectFit: 'contain',
        }}
      />
    </div>
        </main>
      </div>
    );
  } else {
    // Trigger
    playbaseData.stop();
    playTrigger();

    return (
      <div className={styles.container}>
        <Head>
          <title>Halloween 2022</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>

         

        <div style={{ position: 'relative', width: "100vw", height: '100vh' }}>
      <Image
        alt="Mountains"
        src="/angry-pumpkin.gif"
        fill
        sizes="100vw"
        style={{
          objectFit: 'contain',
        }}
      />
    </div>
        </main>
      </div>
    );
  }
}
