import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'

export default function Home() {
  const fetcher = (url:string) => fetch(url).then((res) => res.json());

  const { data, error } = useSWR('/api/trigger', fetcher, { refreshInterval: 1000 });

  if (error) return "An error has occurred.";
  if (!data) return "Loading...";
  if (data) console.log("Data", data);
  if (data) console.log("Data Trigger", data.trigger);

  if( data.trigger) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Halloween 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       
        <Image src="/pumpkin.gif" alt="pumpkin" fill/>
    
        
      </main>

    </div>
  ) }
  else { 
    return (
      <div className={styles.container}>
        <Head>
          <title>Halloween 2022</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
         
          <Image src="/cat-pumpkin.gif" alt="pumpkin" fill/>
      
          
        </main>
  
      </div>
    )

  }
}
