import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Trigger() {
 
  async function handleClick() {

    const res = await fetch('/api/trigger', {method: 'POST'});
    // The return value is *not* serialized
    // You can return Date, Map, Set, etc.
    console.log( "Responze", res);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Halloween 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       
            <button onClick={handleClick}> Press Me!</button>
        
      </main>

      
    </div>
  )
}
